# # github
TWITTER_KEY: TU46hFfcshHMu9EhfgIM06eur
TWITTER_SECRET:	DTkQ7hnh1kGlAkQCsXAETlOUchxfps53RO4FNDAjD0OWUTalIr
ACCESS_TOKEN: 2745200593-GAVy7BfxOEL5ItLgypNAoZhTEuEuPHvkES3ucs8
ACCESS_TOKEN_SECRET: t3ecW7V9U0lA5A4K6AFdbMEPBBZF4oJ7xKFZRRNeDZofW

# Bruno
# TWITTER_KEY: 6B4MCjrebrhTobrqjINZ70nax
# TWITTER_SECRET: dwNInLAyfoN7iFN9zhjzXclahYuTVM9TicnsECrVv8nykK1He9
# ACCESS_TOKEN: 2595366482-bKYvMIueSJpp7KqHySW3lgZDYrPepjDke7Z6n6E
# ACCESS_TOKEN_SECRET: aH9QMLZpWId9nHLlrwcpgTmkibH7yJJrddLQaKdugVC9M